import pandas as pd
import pandas_ta as ta

def add_technical_indicators(df):
    """
    Adds technical indicators to the DataFrame using pandas-ta.
    Expects columns: 'open', 'high', 'low', 'close', 'volume'.
    """
    # Ensure all columns are lowercase for pandas-ta
    df.columns = [c.lower() for c in df.columns]
    
    # 1. RSI (Relative Strength Index)
    # Momentum indicator to identify overbought/oversold conditions
    df['rsi'] = ta.rsi(df['close'], length=14)
    
    # 2. MACD (Moving Average Convergence Divergence)
    # Trend-following momentum indicator
    # Returns macd, histogram, signal columns
    macd = ta.macd(df['close'], fast=12, slow=26, signal=9)
    if macd is not None:
        df = pd.concat([df, macd], axis=1)
        # Rename for clarity if needed, but default names are usually:
        # MACD_12_26_9, MACDh_12_26_9, MACDs_12_26_9
    
    # 3. EMA (Exponential Moving Averages)
    # Trend indicators
    df['ema_7'] = ta.ema(df['close'], length=7)
    df['ema_25'] = ta.ema(df['close'], length=25)
    df['ema_99'] = ta.ema(df['close'], length=99)
    
    # 4. ATR (Average True Range)
    # Volatility indicator
    df['atr'] = ta.atr(df['high'], df['low'], df['close'], length=14)
    
    # 5. Volume Moving Average
    df['vol_ma_20'] = ta.sma(df['volume'], length=20)
    
    # Drop NaN values generated by indicators (e.g., first 99 rows for EMA_99)
    df.dropna(inplace=True)
    
    return df

def get_feature_columns():
    """Returns the list of feature columns to be used for training."""
    # We exclude 'timestamp' and target 'close' from inputs if we are predicting 'close'
    # But for LSTM, 'close' IS a feature for the next step.
    
    return [
        'close', 'high', 'low', 'open', 'volume',
        'rsi', 
        'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 
        'ema_7', 'ema_25', 'ema_99', 
        'atr', 'vol_ma_20'
    ]
