import pandas as pd
import numpy as np

def add_technical_indicators(df):
    Expects columns: 'open', 'high', 'low', 'close', 'volume'.
    """
    # Ensure all columns are lowercase
    df.columns = [c.lower() for c in df.columns]
    
    # --- 1. RSI (Relative Strength Index) ---
    # Formula: 100 - (100 / (1 + RS))
    delta = df['close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    
    rs = gain / loss
    df['rsi'] = 100 - (100 / (1 + rs))
    # Fill NaN from initial calculation to avoid dropping too much data early on if preferred, 
    # but strictly we drop later.
    
    # --- 2. MACD (Moving Average Convergence Divergence) ---
    # EMA_12 - EMA_26
    ema_12 = df['close'].ewm(span=12, adjust=False).mean()
    ema_26 = df['close'].ewm(span=26, adjust=False).mean()
    
    df['MACD_12_26_9'] = ema_12 - ema_26
    df['MACDs_12_26_9'] = df['MACD_12_26_9'].ewm(span=9, adjust=False).mean()
    df['MACDh_12_26_9'] = df['MACD_12_26_9'] - df['MACDs_12_26_9']
    
    # --- 3. EMA (Exponential Moving Averages) ---
    df['ema_7'] = df['close'].ewm(span=7, adjust=False).mean()
    df['ema_25'] = df['close'].ewm(span=25, adjust=False).mean()
    df['ema_99'] = df['close'].ewm(span=99, adjust=False).mean()
    
    # --- 4. ATR (Average True Range) ---
    # TR = Max(High-Low, Abs(High-PrevClose), Abs(Low-PrevClose))
    high_low = df['high'] - df['low']
    high_close = (df['high'] - df['close'].shift()).abs()
    low_close = (df['low'] - df['close'].shift()).abs()
    
    tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
    df['atr'] = tr.rolling(window=14).mean()
    
    # --- 5. Volume Moving Average ---
    df['vol_ma_20'] = df['volume'].rolling(window=20).mean()
    
    # Drop NaN values generated by indicators (especially EMA_99)
    df.dropna(inplace=True)
    
    return df

def get_feature_columns():
    """Returns the list of feature columns to be used for training."""
    # We exclude 'timestamp' and target 'close' from inputs if we are predicting 'close'
    # But for LSTM, 'close' IS a feature for the next step.
    
    return [
        'close', 'high', 'low', 'open', 'volume',
        'rsi', 
        'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 
        'ema_7', 'ema_25', 'ema_99', 
        'atr', 'vol_ma_20'
    ]
